repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black --check .
        language: python
        types: [python]
    -   id: isort
        name: isort
        entry: isort --profile black --check .
        language: python
        types: [python]
    -   id: flake8
        name: flake8
        entry: flake8 .
        language: python
        types: [python]
